# Generated by Django 4.1.7 on 2023-06-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='commented_by',
        ),
    ]
